version: '3'

services:
        db:
                image: vitallish/mta-app-db
                restart: always
                command: --default-authentication-plugin=mysql_native_password
                env_file:
                        - mta-app-constants.env
                ports: 
                        - "33061:3306"
        app-build:
                image: vitallish/mta-app
                restart: on-failure
                command: ["python", "./load_defs.py"]
                env_file:
                        - mta-app-constants.env
                depends_on:
                        - db
