-- MySQL Script generated by MySQL Workbench
-- 01/29/16 23:11:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mta_trains
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mta_trains
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mta_trains` DEFAULT CHARACTER SET utf8 ;
USE `mta_trains` ;

-- -----------------------------------------------------
-- Table `mta_trains`.`trainID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mta_trains`.`trainID` (
  `full_id` VARCHAR(45) NOT NULL COMMENT '',
  `route_plan` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `direction` ENUM('N','S') NULL DEFAULT NULL COMMENT '',
  `start_date` DATE NULL DEFAULT NULL COMMENT '',
  `route_id` VARCHAR(2) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`full_id`)  COMMENT '',
  UNIQUE INDEX `full_id_UNIQUE` (`full_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mta_trains`.`enroute_trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mta_trains`.`enroute_trains` (
  `full_id` VARCHAR(45) NOT NULL COMMENT '',
  `stop_id` VARCHAR(4) NOT NULL COMMENT '',
  `current_status` ENUM('INCOMING_AT','STOPPED_AT','IN_TRANSIT_TO') NULL DEFAULT NULL COMMENT '',
  `last_ping` DATETIME NULL DEFAULT NULL COMMENT '',
  `timeFeed` DATETIME NULL DEFAULT NULL COMMENT '',
  `stop_sequence` INT(2) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`full_id`)  COMMENT '',
  UNIQUE INDEX `full_id_UNIQUE` (`full_id` ASC)  COMMENT '',
  INDEX `stops_idx` (`stop_id` ASC)  COMMENT '',
  CONSTRAINT `full_id`
    FOREIGN KEY (`full_id`)
    REFERENCES `mta_trains`.`trainID` (`full_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mta_trains`.`stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mta_trains`.`stops` (
  `stop_id` VARCHAR(4) NOT NULL COMMENT '',
  `stop_name` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  `stop_lat` DOUBLE NULL DEFAULT NULL COMMENT '',
  `stop_lon` DOUBLE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`stop_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mta_trains`.`sched_stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mta_trains`.`sched_stops` (
  `full_stop_id` VARCHAR(49) NOT NULL COMMENT '',
  `full_id` VARCHAR(45) NOT NULL COMMENT '',
  `stop_id` VARCHAR(4) NOT NULL COMMENT '',
  `arrival` DATETIME NULL DEFAULT NULL COMMENT '',
  `departure` DATETIME NULL DEFAULT NULL COMMENT '',
  `timeFeed` DATETIME NOT NULL COMMENT '',
  `enroute_conf` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`full_stop_id`)  COMMENT '',
  UNIQUE INDEX `row_id_UNIQUE` (`full_stop_id` ASC)  COMMENT '',
  INDEX `stops_idx` (`stop_id` ASC)  COMMENT '',
  INDEX `trainID` (`full_id` ASC)  COMMENT '',
  CONSTRAINT `trainID`
    FOREIGN KEY (`full_id`)
    REFERENCES `mta_trains`.`trainID` (`full_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stops`
    FOREIGN KEY (`stop_id`)
    REFERENCES `mta_trains`.`stops` (`stop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
